"""initials again

Revision ID: 8491e4691e08
Revises: 
Create Date: 2025-05-17 12:06:05.362752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8491e4691e08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('emotion', sa.String(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('model_path', sa.String(), nullable=True),
    sa.Column('total_data', sa.Integer(), nullable=True),
    sa.Column('test_size', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('train_time', sa.Float(), nullable=True),
    sa.Column('prior_probabilities_path', sa.String(), nullable=True),
    sa.Column('word_probabilities_path', sa.String(), nullable=True),
    sa.Column('tfidf_details_path', sa.String(), nullable=True),
    sa.Column('bert_lexicon_details_path', sa.String(), nullable=True),
    sa.Column('evaluation_metrics_path', sa.String(), nullable=True),
    sa.Column('predict_results_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_table('preprocessed_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('preprocessed_text', sa.String(), nullable=True),
    sa.Column('emotion', sa.String(), nullable=False),
    sa.Column('is_preprocessed', sa.Boolean(), nullable=True),
    sa.Column('is_trained', sa.Boolean(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preprocessed_datasets_id'), 'preprocessed_datasets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preprocessed_datasets_id'), table_name='preprocessed_datasets')
    op.drop_table('preprocessed_datasets')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
