"""tambah kolom is_training_data

Revision ID: d71119be2004
Revises: 8d827b7a5ee3
Create Date: 2025-05-12 09:45:39.352262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71119be2004'
down_revision: Union[str, None] = '8d827b7a5ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_result', sa.Column('is_training_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process_result', 'is_training_data')
    op.drop_constraint('uix_confusion_matrix', 'confusion_matrix', type_='unique')
    op.drop_constraint('uix_class_metrics', 'class_metrics', type_='unique')
    # ### end Alembic commands ###
